<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>About Us</title>
    <script src="https://kit.fontawesome.com/d13ee8b9fd.js" crossorigin="anonymous"></script>

</head>
<style>
    .topimg{
        background-image: url(images/aboutuustop.jpg);
        margin-top: -30px;
        height: 320px;
        width: 100%;
    }
    .topimg h1{
        padding-top: 120px;
        text-align: center;
        font-size: 70px;
        color: white;
    }
    .us{
        background-color: black;
        color: white;
        text-align: center;
        font-size: 50px;
    }
    .us a{
    float:right;
    padding-right:30px;
    padding-top:10px;
    matgin:5px;
    font-size:35px;
    }
    .about1 img{
        float: left;
        height: 370px;
        margin-right: 80px;
        border: 2px solid black;
    }
    .description p{
        text-align: justify;
        font-size: 20px;
    }
    .description{
        border-bottom: 2px solid black;
    }
    .description h1{
        margin-left: 600px;
    }
    .driverimg img{
        float: right;
    }
    .driver p{
        font-size: 20px;

    }
    .driver img{
        height: 400px;
        

    }
    .top2{
        background-image: url(images/aboutustop2.jpg);
        height: 500px;
        width: 100%;
    }
    .top2 h1{
        text-align: center;
        padding-top: 120px;
        font-size: 70px;
        color: white;
    }
    .top3{
        background-image: url(images/carabout2.1.jpg);
        height: 400px;
    }
    .top3 h1{
        text-align: center;
        padding-top: 200px;
        font-size: 80px;
        color: white;
    }
    .driverinfo img{
        float: right;
    }
    #famimg img{
        height: 400px;
        width: 500px;
        float: right;
        margin-top: -200px;
    }
    .row{
    display: flex;
    flex-wrap: wrap;
}
ul{
    list-style: none;
}
.footer-col{
    width: 25%;
    padding: 0 15px;
    color: white;
}
a{
    text-decoration: none;
    color:grey;
    font-weight: 300;
}
.contain{
    background-color: black;
    height: 300px;
}
li{
    margin-bottom: 20px;
}
.footer-col ul li :hover{
    padding: 10px;

}
</style>
<body>
    <div class="us">About Us
    <a href="Home.html" style="color: white;">Back</a>
    </div>
    <div class="topimg">
        <h1> Who We Are </h1>
    </div>
    <div class="description">
        <h1>About</h1>
        
        <div class="about1">
            <img src="images/about-1.jpg" alt="">
        </div>
        <p style="margin-left: 600px;">VAHAN is India’s coolest mobility platform and one of the world’s largest ride-hailing companies, <br> 250+ cities across India, Australia, New Zealand, and the UK. The VAHAN website offers mobility <br> solutions by connecting customers to drivers and a wide range of vehicles across bikes, auto-rickshaws,<br> metered taxis, and cabs, enabling convenience and transparency for hundreds of millions of consumers and <br> over 1.5 million driver-partners.<br>

            VAHAN's core mobility offering in India is supplemented by its electric-vehicle arm, <br>VAHAN Electric; India’s largest fleet management business,VAHAN Fleet Technologies and VAHAN Skilling,<br> that aims to enable millions of livelihood opportunities for India's youth. <br>With its acquisition of Ridlr, India’s leading public transportation website and investment in Vogo, a dockless scooter sharing solution,<br> VAHAN is looking to build mobility for the next billion Indians.<br> VAHAN also extends its consumer offerings like micro-insurance and credit led payments<br> through VAHAN Financial Services and a range of owned food brands through India’s largest network of kitchens<br> under its Food business.<br>
            
            VAHAN was founded in March 2023 by Abhilash Pal with a mission to provide a better performance and features to travel industry.
            </p>
    </div>
    <div class="driver">
        <div class="top2">
            <h1>Let's Take A Ride</h1>

       </div>
        <div class="driverimg">
            <br/><img src="images/famimg1.1.jpg" alt="">
        </div>
        <h1>Features</h1>
        <p>Cab Management System helps to undertake automate streamlining of cabs for the routes generated by admin. The system includes driver management, drop point management, vehicle management and booking system. This application can be used for administering the internal office cabs.</p>
        <p>As taxi services are available 24/7, you can enjoy a taxi ride any time or during transportation emergencies. Whether you are traveling in a new place or in emergency situations, taxi cab services will help you to reach your destination safely and on time.</p>
        <p>Economic & Affordable. With regard to ease and comfort, taxi services are the most economic and affordable form of transportation.</p>
        <p>Saves Time. Hiring a taxi service saves a great deal of time and energy.</p>
        <p>Professional and experienced drivers.</p>
        <p></p>
    <div class="top3">
        <h1>Reach In Time </h1>
    </div>
    <div class="driverinfo">
        <br/><img src="images/driver.jpg" alt="">
    </div>
    <h1>Drivers Skills </h1> 
    <p>To be a confident driver who is able to drive well in any road and weather conditions.</p>
        <p>a helpful, trustworthy and patient manner.</p>
        <p>some number skills, as you'll be dealing with cash a lot.</p>
        <p>to be able to deal with all types of people including the occasional awkward or difficult customer.</p>
        <p>Strong driving record,Navigation.</p>
        <p> Basic maintenance knowledge.</p>
        <p> Physical fitness and strength.</p>
        <p>fficiency and time-management And Problem-solving, Detail-oriented.</p>
    </div>
    <div class="footer">
        <div class="contain">
            <div class="row">
                <div class="footer-col">
                    <h4>Compuny</h4>
                    <ul>
                        <li><a href="About.jsp">About Us</a></li>
                        <li><a href="Contact.jsp">Contact Us</a></li>
                        <li><a href="Services.jsp">Our services</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>get help </h4>
                    <ul>
                        <li><a href="Faq.jsp">FAQ</a></li>
                        <li><a href="Blog.jsp">Blog</a></li>
                        <li><a href="Privacy.jsp">Privacy And Policy</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>Booking Systems</h4>
                    <ul>
                        <li><a href="Home.html">Book A cab</a></li>
                        <li><a href="login.jsp">Sign Up</a></li>
                    </ul>
                </div>
                <div class="social-links">
                    <h4 style="color: white;">Social Media</h4>
                    <ul style="color: white;">
                        <li><a href="#"><i class="fa-brands fa-square-whatsapp"></i></a></li>
                        <li><a href="#"><i class="fa-brands fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa-brands fa-youtube"></i></a></li>
                        <li><a href="#"></a><i class="fa-brands fa-twitter"></i></li>
                        <li><a href="#"><i class="fa-brands fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</body>
</html>